// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBAA9C9aDoyZ83tTHe_o0QOyVA1gImfs',
    appId: '1:537891335138:web:280a62eee54fb189ed27bb',
    messagingSenderId: '537891335138',
    projectId: 'association--app',
    authDomain: 'association--app.firebaseapp.com',
    storageBucket: 'association--app.appspot.com',
    measurementId: 'G-PMFD0YN66N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoxLudRt9fnsrf0ztPwWJnPTFdlqnQ08',
    appId: '1:537891335138:android:e2f93d43a8228c69ed27bb',
    messagingSenderId: '537891335138',
    projectId: 'association--app',
    storageBucket: 'association--app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfO8Mjg2QFL14BMZPs0NrarazJSCNU9U',
    appId: '1:537891335138:ios:348897c279ad98d3ed27bb',
    messagingSenderId: '537891335138',
    projectId: 'association--app',
    storageBucket: 'association--app.appspot.com',
    iosBundleId: 'com.association.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzfO8Mjg2QFL14BMZPs0NrarazJSCNU9U',
    appId: '1:537891335138:ios:348897c279ad98d3ed27bb',
    messagingSenderId: '537891335138',
    projectId: 'association--app',
    storageBucket: 'association--app.appspot.com',
    iosBundleId: 'com.association.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBAA9C9aDoyZ83tTHe_o0QOyVA1gImfs',
    appId: '1:537891335138:web:2679235a44f55994ed27bb',
    messagingSenderId: '537891335138',
    projectId: 'association--app',
    authDomain: 'association--app.firebaseapp.com',
    storageBucket: 'association--app.appspot.com',
    measurementId: 'G-88WT6V4050',
  );

}