// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqu1K78qt5VQ8xfa2Nsr_z3X6GjItW7To',
    appId: '1:917418976960:web:a32f8b79989327b6162f25',
    messagingSenderId: '917418976960',
    projectId: 'association-app-madrasa',
    authDomain: 'association-app-madrasa.firebaseapp.com',
    storageBucket: 'association-app-madrasa.firebasestorage.app',
    measurementId: 'G-KST0BEW4GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMS-TvEhIcMpawYiYTlp40p1NyCbSpf1o',
    appId: '1:917418976960:android:0b9cd3a35577fb53162f25',
    messagingSenderId: '917418976960',
    projectId: 'association-app-madrasa',
    storageBucket: 'association-app-madrasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjyWOIcTz6U6LCn-Dt9QRHvaTktsjC2k',
    appId: '1:917418976960:ios:9526fe0767ca6a30162f25',
    messagingSenderId: '917418976960',
    projectId: 'association-app-madrasa',
    storageBucket: 'association-app-madrasa.firebasestorage.app',
    iosBundleId: 'com.association.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_NEW_CLIENT_API_KEY',
    appId: 'YOUR_NEW_CLIENT_APP_ID',
    messagingSenderId: 'YOUR_NEW_CLIENT_SENDER_ID',
    projectId: 'YOUR_NEW_CLIENT_PROJECT_ID',
    storageBucket: 'YOUR_NEW_CLIENT_STORAGE_BUCKET',
    iosBundleId: 'com.association.app.madraha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_NEW_CLIENT_API_KEY',
    appId: 'YOUR_NEW_CLIENT_APP_ID',
    messagingSenderId: 'YOUR_NEW_CLIENT_SENDER_ID',
    projectId: 'YOUR_NEW_CLIENT_PROJECT_ID',
    authDomain: 'YOUR_NEW_CLIENT_AUTH_DOMAIN',
    storageBucket: 'YOUR_NEW_CLIENT_STORAGE_BUCKET',
    measurementId: 'YOUR_NEW_CLIENT_MEASUREMENT_ID',
  );
}